In [1]:
from main_functions import *
from numba import njit

In [4]:
g_sl4_1 = np.array([1,12,14,15], dtype=np.int32) #1-graded (1,12,14,15)
g_sl4_2 = np.array([2,4,11,13], dtype=np.int32) #2-graded (2,4,11,13)
g_sl4_3 = np.array([3,5,6,10], dtype=np.int32) #3-graded (3,5,6,10)
g_sl4_4 = np.array([7,8,9], dtype=np.int32) #4-graded (7,8,9)
g_sl4 = np.array([g_sl4_1,g_sl4_2,g_sl4_3,g_sl4_4], dtype=object); 
g_sl4

array([array([ 1, 12, 14, 15], dtype=int32),
       array([ 2,  4, 11, 13], dtype=int32),
       array([ 3,  5,  6, 10], dtype=int32),
       array([7, 8, 9], dtype=int32)], dtype=object)

In [5]:
# g = g^1 + g^2 + g^3 + g^4, we order them g^1, g^2, g^3, g^4, 
# where 
# g^1 = span(e_1, e_12, e_14, e_15), 
# g^2 = span(e_2, e_4, e_11, e_13), 
# g^3 = span(e_3, e_5, e_6, e_10), 
# g^4 = span(e_7, e_8, e_9)
# so the prefered order is: 
# e_1 (1st), e_12 (2nd), e_14 (3rd), e_15 (4th),
# e_2 (5th), e_4 (6th), e_11 (7th), e_13 (8th),
# e_3 (9th), e_5 (10th), e_6 (11th), e_10 (12th),
# e_7 (13th), e_8 (14th), e_9 (15th)
# i.e., in a zero indexed list:
# (e_1 =) 1-->0, (e_2 =) 2-->4, 3-->8, 4-->5, 5-->9, 6-->10, 7-->12, 8-->13, 
# 9-->14, 10-->11, 11-->6, 12-->1, 13-->7, 14-->2, 15-->3
e_sort_sl4 = np.array([0,4,8,5,9,10,12,13,14,11,6,1,7,2,3], dtype=np.int32)

In [8]:
@njit
def commutator(a, b):
    sign = 1
    if a > b:
        a,b = b,a
        sign = -1
    # to make it easier later, we return lists with the answers, where a x+y = [x,y]
    if a==1 and b==10:
        return [(-sign,9),(-sign,8),(-sign,7)]
    elif a==1 and b==11:
        return [(-sign,3)]
    elif a==1 and b==12:
        return [(-sign,2)]
    elif a==1 and b==13:
        return [(sign,6)]
    elif a==1 and b==15:
        return [(sign,4)]
    elif a==2 and b==13:
        return [(-sign,8),(-sign,7)]
    elif a==2 and b==14:
        return [(-sign,3)]
    elif a==2 and b==15:
        return [(sign,5)]
    elif a==3 and b==15:
        return [(-sign,7)]
    elif a==4 and b==11:
        return [(-sign,9),(-sign,8)]
    elif a==4 and b==12:
        return [(-sign,5)]
    elif a==4 and b==14:
        return [(sign,6)]
    elif a==5 and b==14:
        return [(-sign,8)]      
    elif a==6 and b==12:
        return [(-sign,9)]
    elif a==11 and b==15:
        return [(-sign,10)]
    elif a==12 and b==13:
        return [(-sign,10)]
    elif a==12 and b==14:
        return [(-sign,11)]
    elif a==14 and b==15:
        return [(-sign,13)]
    else:
        return [(0,0)]

In [9]:
# We call commutator so it compiles. 
commutator(1, 11)

[(-1, 3)]

In [13]:
#%%time
#print_cohomology(27, 7, g_sl4, e_sort_sl4, commutator)

# The implementation finding smith normal form in Sympy is too slow making this untennable 